plugins { id 'com.android.application' }

android {
    namespace 'uy.federico.mispartidos'
    compileSdk 35

    signingConfigs {
        stable {
            storeFile file(System.getenv('MISPARTIDOS_KEYSTORE_PATH') ?: 'missing-release-key.jks')
            storePassword System.getenv('MISPARTIDOS_STORE_PASSWORD')
            keyAlias System.getenv('MISPARTIDOS_KEY_ALIAS')
            keyPassword System.getenv('MISPARTIDOS_KEY_PASSWORD')
        }
    }

    defaultConfig {
        applicationId 'uy.federico.mispartidos'
        minSdk 26
        targetSdk 35
        versionCode 29
        versionName '0.9.15'
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.stable
        }
    }

}
